// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         truck_id: "truck_id"
 *     }
 */
export interface GetTruckTrucksTruckIdGetRequest {
    truck_id: string;
}
