// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         truck_id: "truck_id"
 *     }
 */
export interface GetTruckMenuTrucksTruckIdMenuGetRequest {
    truck_id: string;
    /** Only show items at or below this price ($) */
    max_price?: number | null;
}
