// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListMenuItemsMenuItemsGetRequest {
    /** Minimum price ($) */
    min_price?: number | null;
    /** Maximum price ($) */
    max_price?: number | null;
    /** Filter by category (e.g. 'cone', 'bar', 'specialty') */
    category?: string | null;
}
