// This file was auto-generated by Fern from our API Definition.

import type * as IceCreamClient from "../index.js";

export interface HttpValidationError {
    detail?: IceCreamClient.ValidationError[] | undefined;
}
