// This file was auto-generated by Fern from our API Definition.

import type * as ScoopsOnWheels from "../index.js";

export interface HttpValidationError {
    detail?: ScoopsOnWheels.ValidationError[] | undefined;
}
