// This file was auto-generated by Fern from our API Definition.

import type * as IceCreamClient from "../index.js";

/**
 * A truck's full menu.
 */
export interface Menu {
    truck_id: string;
    truck_name: string;
    items: IceCreamClient.MenuItem[];
}
