// This file was auto-generated by Fern from our API Definition.

/**
 * A single item on a truck's menu.
 */
export interface MenuItem {
    /** Unique item identifier */
    id: string;
    /** ID of the truck that sells this item */
    truck_id: string;
    /** Item display name */
    name: string;
    /** Short description of the item */
    description: string;
    /** Price in USD */
    price: number;
    /** Item category: 'cone', 'bar', 'cup', 'specialty', 'drink' */
    category: string;
    /** Whether the item is currently in stock */
    is_available: boolean;
    /** Common allergens present */
    allergens?: string[] | undefined;
}
