// This file was auto-generated by Fern from our API Definition.

import type * as ScoopsOnWheels from "../index.js";

/**
 * A single truck result with computed distance.
 */
export interface SearchResult {
    truck: ScoopsOnWheels.Truck;
    /** Distance from the search origin in miles */
    distance_miles: number;
}
