// This file was auto-generated by Fern from our API Definition.

import type * as ScoopsOnWheels from "../index.js";

/**
 * Paginated search response.
 */
export interface SearchResults {
    /** Number of trucks matching the query */
    total: number;
    filters: ScoopsOnWheels.SearchFilters;
    results: ScoopsOnWheels.SearchResult[];
}
