// This file was auto-generated by Fern from our API Definition.

import type * as IceCreamClient from "../index.js";

/**
 * Paginated search response.
 */
export interface SearchResults {
    /** Number of trucks matching the query */
    total: number;
    filters: IceCreamClient.SearchFilters;
    results: IceCreamClient.SearchResult[];
}
