// This file was auto-generated by Fern from our API Definition.

/**
 * Echo of the filters used in a search request.
 */
export interface SearchFilters {
    latitude: number;
    longitude: number;
    radius_miles: number;
    min_price?: (number | null) | undefined;
    max_price?: (number | null) | undefined;
    flavor?: (string | null) | undefined;
    is_open?: (boolean | null) | undefined;
}
