// This file was auto-generated by Fern from our API Definition.

/**
 * Lightweight truck representation used in list responses.
 */
export interface TruckSummary {
    /** Unique truck identifier (slug) */
    id: string;
    /** Truck display name */
    name: string;
    /** Whether the truck is currently serving customers */
    is_open: boolean;
    /** Current GPS latitude */
    latitude: number;
    /** Current GPS longitude */
    longitude: number;
    /** Human-readable neighborhood name */
    neighborhood: string;
}
