// This file was auto-generated by Fern from our API Definition.

/**
 * Full truck details including contact info and hours.
 */
export interface Truck {
    /** Unique truck identifier (slug) */
    id: string;
    /** Truck display name */
    name: string;
    /** Whether the truck is currently serving customers */
    is_open: boolean;
    /** Current GPS latitude */
    latitude: number;
    /** Current GPS longitude */
    longitude: number;
    /** Human-readable neighborhood name */
    neighborhood: string;
    /** Truck marketing tagline */
    tagline: string;
    /** Contact phone number */
    phone: string;
    /** Operating hours description */
    hours: string;
    /** Whether the truck accepts card payments */
    accepts_card: boolean;
    /** Average customer rating (1–5) */
    rating: number;
    /** Number of customer reviews */
    review_count: number;
    /** Signature items or flavors this truck is known for */
    specialties: string[];
}
