// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         latitude: 1.1,
 *         longitude: 1.1
 *     }
 */
export interface SearchNearbyTrucksSearchNearbyGetRequest {
    /** Your current latitude (e.g. 40.7128) */
    latitude: number;
    /** Your current longitude (e.g. -74.0060) */
    longitude: number;
    /** Search radius in miles */
    radius_miles?: number;
    /** Minimum item price filter ($) */
    min_price?: number | null;
    /** Maximum item price filter ($) */
    max_price?: number | null;
    /** Filter trucks that carry this flavor */
    flavor?: string | null;
    /** Only show currently open trucks */
    is_open?: boolean | null;
}
