// This file was auto-generated by Fern from our API Definition.

import * as IceCreamClient from "../../src/api/index";
import { IceCreamClientClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("MenuClient", () => {
    test("getTruckMenu (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IceCreamClientClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            truck_id: "truck_id",
            truck_name: "truck_name",
            items: [
                {
                    id: "id",
                    truck_id: "truck_id",
                    name: "name",
                    description: "description",
                    price: 1.1,
                    category: "category",
                    is_available: true,
                    allergens: ["allergens"],
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/trucks/truck_id/menu")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.menu.getTruckMenu({
            truck_id: "truck_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getTruckMenu (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IceCreamClientClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/trucks/truck_id/menu")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.menu.getTruckMenu({
                truck_id: "truck_id",
            });
        }).rejects.toThrow(IceCreamClient.UnprocessableEntityError);
    });

    test("listMenuItems (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IceCreamClientClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = [
            {
                id: "id",
                truck_id: "truck_id",
                name: "name",
                description: "description",
                price: 1.1,
                category: "category",
                is_available: true,
                allergens: ["allergens"],
            },
        ];

        server.mockEndpoint().get("/menu/items").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.menu.listMenuItems();
        expect(response).toEqual(rawResponseBody);
    });

    test("listMenuItems (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IceCreamClientClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/menu/items").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.menu.listMenuItems();
        }).rejects.toThrow(IceCreamClient.UnprocessableEntityError);
    });
});
