// This file was auto-generated by Fern from our API Definition.

import * as ScoopsOnWheels from "../../src/api/index";
import { ScoopsOnWheelsClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SearchClient", () => {
    test("searchNearby (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ScoopsOnWheelsClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            total: 1,
            filters: {
                latitude: 1.1,
                longitude: 1.1,
                radius_miles: 1.1,
                min_price: 1.1,
                max_price: 1.1,
                flavor: "flavor",
                is_open: true,
            },
            results: [
                {
                    truck: {
                        id: "id",
                        name: "name",
                        is_open: true,
                        latitude: 1.1,
                        longitude: 1.1,
                        neighborhood: "neighborhood",
                        tagline: "tagline",
                        phone: "phone",
                        hours: "hours",
                        accepts_card: true,
                        rating: 1.1,
                        review_count: 1,
                        specialties: ["specialties"],
                    },
                    distance_miles: 1.1,
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/trucks/search/nearby")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.search.searchNearby({
            latitude: 1.1,
            longitude: 1.1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("searchNearby (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ScoopsOnWheelsClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/trucks/search/nearby")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.search.searchNearby({
                latitude: 1.1,
                longitude: 1.1,
            });
        }).rejects.toThrow(ScoopsOnWheels.UnprocessableEntityError);
    });
});
