// This file was auto-generated by Fern from our API Definition.

import { IceCreamClientClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SystemClient", () => {
    test("health", async () => {
        const server = mockServerPool.createServer();
        const client = new IceCreamClientClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/health").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.system.health();
        expect(response).toEqual(rawResponseBody);
    });
});
