// This file was auto-generated by Fern from our API Definition.

import * as IceCreamClient from "../../src/api/index";
import { IceCreamClientClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TrucksClient", () => {
    test("listTrucks", async () => {
        const server = mockServerPool.createServer();
        const client = new IceCreamClientClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = [
            { id: "id", name: "name", is_open: true, latitude: 1.1, longitude: 1.1, neighborhood: "neighborhood" },
        ];

        server.mockEndpoint().get("/trucks").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.trucks.listTrucks();
        expect(response).toEqual(rawResponseBody);
    });

    test("getTruck (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IceCreamClientClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            name: "name",
            is_open: true,
            latitude: 1.1,
            longitude: 1.1,
            neighborhood: "neighborhood",
            tagline: "tagline",
            phone: "phone",
            hours: "hours",
            accepts_card: true,
            rating: 1.1,
            review_count: 1,
            specialties: ["specialties"],
        };

        server.mockEndpoint().get("/trucks/truck_id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.trucks.getTruck({
            truck_id: "truck_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getTruck (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IceCreamClientClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/trucks/truck_id").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.trucks.getTruck({
                truck_id: "truck_id",
            });
        }).rejects.toThrow(IceCreamClient.UnprocessableEntityError);
    });
});
